# Generated by Django 5.2.15 on 2026-07-23 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0003_booking_price_snapshot"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="rejection_note",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        migrations.AddField(
            model_name="booking",
            name="rejection_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("dates_unavailable", "Dates no longer available"),
                    ("listing_unavailable", "Listing temporarily unavailable"),
                    ("tenant_requirements_not_met", "Tenant doesn't meet requirements"),
                    ("suspicious_request", "Suspicious or invalid request"),
                    ("other", "Other"),
                ],
                max_length=30,
                null=True,
            ),
        ),
    ]
